/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "tests/test_calc.check" instead.
 */

#include <check.h>
#include <float.h>
#include <math.h>

#include "../reverse_polish_notation.h"

START_TEST(numbers1) {
  char *str = "1234567890";
  double std_result = 1234567890, result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(numbers2) {
  char *str = "103.3456";
  double std_result = 103.3456, result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(numbers3) {
  char *str = "-9.98128234789";
  double std_result = -9.98128234789, result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(numbers4) {
  char *str = "+0.0001234234";
  double std_result = 0.0001234234, result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(numbers5) {
  char *str = "1E3";
  double std_result = 1E3, result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(numbers6) {
  char *str = "123.3456E12";
  double std_result = 123.3456E12, result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(numbers7) {
  char *str = "000000.34234234";
  double std_result = 0.34234234, result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(numbers8) {
  char *str = "-234.234E-11";
  double std_result = -234.234E-11, result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(numbers9) {
  char *str = "334.234E+11";
  double std_result = 334.234E+11, result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(numbers10) {
  char *str = "-234e13";
  double std_result = -234e13, result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST
START_TEST(numbers_incorrect1) {
  char *str = "123,89";
  double result = 0, x = 0;
  int std_error = 1, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(numbers_incorrect2) {
  char *str = "-9.981.28234789";
  double result = 0, x = 0;
  int std_error = 1, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(numbers_incorrect3) {
  char *str = "953E35E";
  double result = 0, x = 0;
  int std_error = 1, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(numbers_incorrect4) {
  char *str = "E3";
  double result = 0, x = 0;
  int std_error = 1, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(numbers_incorrect5) {
  char *str = "..3456E12";
  double result = 0, x = 0;
  int std_error = 1, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(numbers_incorrect6) {
  char *str = " 3456E12";
  double result = 0, x = 0;
  int std_error = 1, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(numbers_incorrect7) {
  char *str = "34 56E12";
  double result = 0, x = 0;
  int std_error = 1, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  ck_assert_int_eq(std_error, error);
}
END_TEST
START_TEST(simple_operation1) {
  char *str = "123.45+987.65";
  double std_result = 123.45 + 987.65, result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(simple_operation2) {
  char *str = "345.78798789-82348788324.234";
  double std_result = 345.78798789 - 82348788324.234, result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(simple_operation3) {
  char *str = "-9.98128234789+34890E2";
  double std_result = -9.98128234789 + 34890E2, result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(simple_operation4) {
  char *str = "-0.0000123-234234.2";
  double std_result = -0.0000123 - 234234.2, result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(simple_operation5) {
  char *str = "--3";
  double std_result = 0 - -3, result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(simple_operation6) {
  char *str = "---++-+-+--+++35897.23";
  double std_result = - - -+ +-+-+- -+ + +35897.23, result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(simple_operation7) {
  char *str = "(+-+0.34234234)";
  double std_result = (+-+0.34234234), result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(simple_operation8) {
  char *str = "9234.23*-289.3";
  double std_result = 9234.23 * -289.3, result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(simple_operation9) {
  char *str = "-23.4*3242.2";
  double std_result = -23.4 * 3242.2, result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(simple_operation10) {
  char *str = "-234e13/68.58";
  double std_result = -234e13 / 68.58, result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(simple_operation11) {
  char *str = "123678.45mod987.65";
  double std_result = fmod(123678.45, 987.65), result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(simple_operation12) {
  char *str = "34242340.0000123mod-234234.2";
  double std_result = fmod(34242340.0000123, -234234.2), result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(simple_operation13) {
  char *str = "345.78798789^4.234";
  double std_result = pow(345.78798789, 4.234), result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(simple_operation14) {
  char *str = "-9.98128234789^-34890E-5";
  double std_result = pow(-9.98128234789, -34890E-5), result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(simple_operation15) {
  char *str = "sin345.092";
  double std_result = sin(345.092), result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(simple_operation16) {
  char *str = "sin(-2942e23)";
  double std_result = sin(-2942e23), result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(simple_operation17) {
  char *str = "sin-3453.092";
  double std_result = sin(-3453.092), result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(simple_operation18) {
  char *str = "cos8345.092";
  double std_result = cos(8345.092), result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(simple_operation19) {
  char *str = "cos(-2942e-3)";
  double std_result = cos(-2942e-3), result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(simple_operation20) {
  char *str = "cos-83453.092";
  double std_result = cos(-83453.092), result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(simple_operation21) {
  char *str = "tan345.092";
  double std_result = tan(345.092), result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(simple_operation22) {
  char *str = "tan(-2942e23)";
  double std_result = tan(-2942e23), result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(simple_operation23) {
  char *str = "tan-3453.092";
  double std_result = tan(-3453.092), result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(simple_operation24) {
  char *str = "asin8345.092";
  double std_result = asin(8345.092), result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(simple_operation25) {
  char *str = "asin(-2942e-3)";
  double std_result = asin(-2942e-3), result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(simple_operation26) {
  char *str = "asin-83453.092";
  double std_result = asin(-83453.092), result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(simple_operation27) {
  char *str = "asin-0.34";
  double std_result = asin(-0.34), result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(simple_operation28) {
  char *str = "asin0.974";
  double std_result = asin(0.974), result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(simple_operation29) {
  char *str = "acos8345.092";
  double std_result = acos(8345.092), result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(simple_operation30) {
  char *str = "acos(-2942e-3)";
  double std_result = acos(-2942e-3), result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(simple_operation31) {
  char *str = "acos-83453.092";
  double std_result = acos(-83453.092), result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(simple_operation32) {
  char *str = "acos-0.34";
  double std_result = acos(-0.34), result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(simple_operation33) {
  char *str = "acos0.974";
  double std_result = acos(0.974), result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(simple_operation34) {
  char *str = "atan8345.092";
  double std_result = atan(8345.092), result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(simple_operation35) {
  char *str = "atan(-2942e-3)";
  double std_result = atan(-2942e-3), result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(simple_operation36) {
  char *str = "atan-83453.092";
  double std_result = atan(-83453.092), result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(simple_operation37) {
  char *str = "atan-0.34";
  double std_result = atan(-0.34), result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(simple_operation38) {
  char *str = "atan0.974";
  double std_result = atan(0.974), result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(simple_operation39) {
  char *str = "sqrt8345.092";
  double std_result = sqrt(8345.092), result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(simple_operation40) {
  char *str = "sqrt(-2942e-3)";
  double std_result = sqrt(-2942e-3), result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(simple_operation41) {
  char *str = "sqrt-83453.092";
  double std_result = sqrt(-83453.092), result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(simple_operation42) {
  char *str = "sqrt-0.34";
  double std_result = sqrt(-0.34), result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(simple_operation43) {
  char *str = "sqrt0.974";
  double std_result = sqrt(0.974), result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(simple_operation44) {
  char *str = "ln8345.092";
  double std_result = log(8345.092), result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(simple_operation45) {
  char *str = "ln(-2942e-3)";
  double std_result = log(-2942e-3), result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(simple_operation46) {
  char *str = "ln-83453.092";
  double std_result = log(-83453.092), result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(simple_operation47) {
  char *str = "ln-0.34";
  double std_result = log(-0.34), result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(simple_operation48) {
  char *str = "ln0.974";
  double std_result = log(0.974), result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(simple_operation49) {
  char *str = "log8345.092";
  double std_result = log10(8345.092), result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(simple_operation50) {
  char *str = "log(-2942e-3)";
  double std_result = log10(-2942e-3), result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(simple_operation51) {
  char *str = "log-83453.092";
  double std_result = log10(-83453.092), result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(simple_operation52) {
  char *str = "log-0.34";
  double std_result = log10(-0.34), result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(simple_operation53) {
  char *str = "log0.974";
  double std_result = log10(0.974), result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(simple_operation54) {
  char *str = "-sin-7";
  double std_result = -sin(-7), result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(simple_operation55) {
  char *str = "(-1)^2";
  double std_result = pow(-1, 2), result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(simple_operation56) {
  char *str = "-(1^-2)";
  double std_result = -pow(1, -2), result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(simple_operation57) {
  char *str = "";
  double std_result = 0, result = 0, x = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST
START_TEST(operation_incorrect1) {
  char *str = "(3";
  double result = 0, x = 0;
  int std_error = 1, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(operation_incorrect2) {
  char *str = ")";
  double result = 0, x = 0;
  int std_error = 1, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(operation_incorrect3) {
  char *str = "456.34)";
  double result = 0, x = 0;
  int std_error = 1, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(operation_incorrect4) {
  char *str = "(456.34)*-234.234)";
  double result = 0, x = 0;
  int std_error = 1, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(operation_incorrect5) {
  char *str = "si3";
  double result = 0, x = 0;
  int std_error = 1, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(operation_incorrect6) {
  char *str = "345modd89";
  double result = 0, x = 0;
  int std_error = 1, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(operation_incorrect7) {
  char *str = "os90";
  double result = 0, x = 0;
  int std_error = 1, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(operation_incorrect8) {
  char *str = "tn90";
  double result = 0, x = 0;
  int std_error = 1, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(operation_incorrect9) {
  char *str = "log10(24 87)";
  double result = 0, x = 0;
  int std_error = 1, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(operation_incorrect10) {
  char *str = "soc(342)";
  double result = 0, x = 0;
  int std_error = 1, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(operation_incorrect11) {
  char *str = "tan9,0";
  double result = 0, x = 0;
  int std_error = 1, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(operation_incorrect12) {
  char *str = "5**82";
  double result = 0, x = 0;
  int std_error = 1, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(operation_incorrect13) {
  char *str = "-234.234//234";
  double result = 0, x = 0;
  int std_error = 1, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(operation_incorrect14) {
  char *str = "23modmod34";
  double result = 0, x = 0;
  int std_error = 1, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(operation_incorrect15) {
  char *str = "45mod/234";
  double result = 0, x = 0;
  int std_error = 1, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(operation_incorrect16) {
  char *str = "234^^23";
  double result = 0, x = 0;
  int std_error = 1, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(operation_incorrect17) {
  char *str = "34/*234";
  double result = 0, x = 0;
  int std_error = 1, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(operation_incorrect18) {
  char *str = "-9234^/234";
  double result = 0, x = 0;
  int std_error = 1, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(operation_incorrect19) {
  char *str = "786/^234";
  double result = 0, x = 0;
  int std_error = 1, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(operation_incorrect20) {
  char *str = "sfs7hd872h29h7";
  double result = 0, x = 0;
  int std_error = 1, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(operation_incorrect21) {
  char *str = "s89u9299ij/234s2";
  double result = 0, x = 0;
  int std_error = 1, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(difficult1) {
  char *str =
      "-sin(89.345mod-8.432)*atan(0.5e-1)/45^-2x+(9cosln124-asin0.123"
      "/(sqrt(98.234+xmodlog18---tan-345x+acos0.32)))";
  double x = 68.523567567;
  double std_result =
             -sin(fmod(89.345, -8.432)) * atan(0.5e-1) / pow(45, -2) * x +
             (9 * cos(log(124)) -
              asin(0.123) / (sqrt(98.234 + fmod(x, log10(18)) -
                                  - -tan(-345) * x + acos(0.32)))),
         result = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(difficult2) {
  char *str = "atan(0.5e-1)/45^-2x";
  double x = -34.123;
  double std_result = atan(0.5e-1) / pow(45, -2) * x, result = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(difficult3) {
  char *str = "9cosln124-asin0.123";
  double x = -14.123;
  double std_result = 9 * cos(log(124)) - asin(0.123), result = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(difficult4) {
  char *str = "xmodlog18";
  double x = 3.123;
  double std_result = fmod(x, log10(18)), result = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(difficult5) {
  char *str = "sqrt(98.234+xmodlog18---tan-345x+acos0.32)";
  double x = -34.123;
  double std_result =
             sqrt(98.234 + fmod(x, log10(18)) - - -tan(-345) * x + acos(0.32)),
         result = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(difficult6) {
  char *str = "tan-345x+acos0.32";
  double x = -34.123;
  double std_result = tan(-345) * x + acos(0.32), result = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

START_TEST(difficult7) {
  char *str = "xmodlog18---tan-345x+acos0.32";
  double x = -34.123;
  double std_result = fmod(x, log10(18)) - - -tan(-345) * x + acos(0.32),
         result = 0;
  int std_error = 0, error = 0;
  StackOut *stack_output = NULL;
  error = calculateRPN(str, &stack_output, x, &result);
  removeStackOut(stack_output);
  if (std_result == std_result)
    ck_assert_double_eq_tol(std_result, result, 1E-7);
  else
    ck_assert_double_nan(result);
  ck_assert_int_eq(std_error, error);
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("numbers");
  TCase *tc1_2 = tcase_create("numbers_incorrect");
  TCase *tc1_3 = tcase_create("simple_operation");
  TCase *tc1_4 = tcase_create("operation_incorrect");
  TCase *tc1_5 = tcase_create("difficult");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, numbers1);
  tcase_add_test(tc1_1, numbers2);
  tcase_add_test(tc1_1, numbers3);
  tcase_add_test(tc1_1, numbers4);
  tcase_add_test(tc1_1, numbers5);
  tcase_add_test(tc1_1, numbers6);
  tcase_add_test(tc1_1, numbers7);
  tcase_add_test(tc1_1, numbers8);
  tcase_add_test(tc1_1, numbers9);
  tcase_add_test(tc1_1, numbers10);
  suite_add_tcase(s1, tc1_2);
  tcase_add_test(tc1_2, numbers_incorrect1);
  tcase_add_test(tc1_2, numbers_incorrect2);
  tcase_add_test(tc1_2, numbers_incorrect3);
  tcase_add_test(tc1_2, numbers_incorrect4);
  tcase_add_test(tc1_2, numbers_incorrect5);
  tcase_add_test(tc1_2, numbers_incorrect6);
  tcase_add_test(tc1_2, numbers_incorrect7);
  suite_add_tcase(s1, tc1_3);
  tcase_add_test(tc1_3, simple_operation1);
  tcase_add_test(tc1_3, simple_operation2);
  tcase_add_test(tc1_3, simple_operation3);
  tcase_add_test(tc1_3, simple_operation4);
  tcase_add_test(tc1_3, simple_operation5);
  tcase_add_test(tc1_3, simple_operation6);
  tcase_add_test(tc1_3, simple_operation7);
  tcase_add_test(tc1_3, simple_operation8);
  tcase_add_test(tc1_3, simple_operation9);
  tcase_add_test(tc1_3, simple_operation10);
  tcase_add_test(tc1_3, simple_operation11);
  tcase_add_test(tc1_3, simple_operation12);
  tcase_add_test(tc1_3, simple_operation13);
  tcase_add_test(tc1_3, simple_operation14);
  tcase_add_test(tc1_3, simple_operation15);
  tcase_add_test(tc1_3, simple_operation16);
  tcase_add_test(tc1_3, simple_operation17);
  tcase_add_test(tc1_3, simple_operation18);
  tcase_add_test(tc1_3, simple_operation19);
  tcase_add_test(tc1_3, simple_operation20);
  tcase_add_test(tc1_3, simple_operation21);
  tcase_add_test(tc1_3, simple_operation22);
  tcase_add_test(tc1_3, simple_operation23);
  tcase_add_test(tc1_3, simple_operation24);
  tcase_add_test(tc1_3, simple_operation25);
  tcase_add_test(tc1_3, simple_operation26);
  tcase_add_test(tc1_3, simple_operation27);
  tcase_add_test(tc1_3, simple_operation28);
  tcase_add_test(tc1_3, simple_operation29);
  tcase_add_test(tc1_3, simple_operation30);
  tcase_add_test(tc1_3, simple_operation31);
  tcase_add_test(tc1_3, simple_operation32);
  tcase_add_test(tc1_3, simple_operation33);
  tcase_add_test(tc1_3, simple_operation34);
  tcase_add_test(tc1_3, simple_operation35);
  tcase_add_test(tc1_3, simple_operation36);
  tcase_add_test(tc1_3, simple_operation37);
  tcase_add_test(tc1_3, simple_operation38);
  tcase_add_test(tc1_3, simple_operation39);
  tcase_add_test(tc1_3, simple_operation40);
  tcase_add_test(tc1_3, simple_operation41);
  tcase_add_test(tc1_3, simple_operation42);
  tcase_add_test(tc1_3, simple_operation43);
  tcase_add_test(tc1_3, simple_operation44);
  tcase_add_test(tc1_3, simple_operation45);
  tcase_add_test(tc1_3, simple_operation46);
  tcase_add_test(tc1_3, simple_operation47);
  tcase_add_test(tc1_3, simple_operation48);
  tcase_add_test(tc1_3, simple_operation49);
  tcase_add_test(tc1_3, simple_operation50);
  tcase_add_test(tc1_3, simple_operation51);
  tcase_add_test(tc1_3, simple_operation52);
  tcase_add_test(tc1_3, simple_operation53);
  tcase_add_test(tc1_3, simple_operation54);
  tcase_add_test(tc1_3, simple_operation55);
  tcase_add_test(tc1_3, simple_operation56);
  tcase_add_test(tc1_3, simple_operation57);
  suite_add_tcase(s1, tc1_4);
  tcase_add_test(tc1_4, operation_incorrect1);
  tcase_add_test(tc1_4, operation_incorrect2);
  tcase_add_test(tc1_4, operation_incorrect3);
  tcase_add_test(tc1_4, operation_incorrect4);
  tcase_add_test(tc1_4, operation_incorrect5);
  tcase_add_test(tc1_4, operation_incorrect6);
  tcase_add_test(tc1_4, operation_incorrect7);
  tcase_add_test(tc1_4, operation_incorrect8);
  tcase_add_test(tc1_4, operation_incorrect9);
  tcase_add_test(tc1_4, operation_incorrect10);
  tcase_add_test(tc1_4, operation_incorrect11);
  tcase_add_test(tc1_4, operation_incorrect12);
  tcase_add_test(tc1_4, operation_incorrect13);
  tcase_add_test(tc1_4, operation_incorrect14);
  tcase_add_test(tc1_4, operation_incorrect15);
  tcase_add_test(tc1_4, operation_incorrect16);
  tcase_add_test(tc1_4, operation_incorrect17);
  tcase_add_test(tc1_4, operation_incorrect18);
  tcase_add_test(tc1_4, operation_incorrect19);
  tcase_add_test(tc1_4, operation_incorrect20);
  tcase_add_test(tc1_4, operation_incorrect21);
  suite_add_tcase(s1, tc1_5);
  tcase_add_test(tc1_5, difficult1);
  tcase_add_test(tc1_5, difficult2);
  tcase_add_test(tc1_5, difficult3);
  tcase_add_test(tc1_5, difficult4);
  tcase_add_test(tc1_5, difficult5);
  tcase_add_test(tc1_5, difficult6);
  tcase_add_test(tc1_5, difficult7);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
