FROM nginx:latest

RUN apt update; \
    apt upgrade; \
    apt install -y gcc libfcgi-dev spawn-fcgi procps; \
    groupadd -g 999 student && \
    useradd -r -u 999 -g student student; \
    chown -R student:student /var/cache/student ; \
    chown -R student:student /var/log/student ; \
    chown -R student:student /etc/nginx/conf.d ; \
    touch /var/run/nginx.pid ; \
    chown -R student:student /var/run/nginx.pid ; \ 
    chmod u-s bin/su; \
    chmod u-s bin/umount; \
    chmod u-s usr/bin/passwd; \
    chmod u-s usr/bin/chfn; \
    chmod u-s bin/mount; \
    chmod g-s usr/bin/chage; \
    chmod u-s usr/bin/chsh; \
    chmod g-s usr/bin/expiry; \
    chmod g-s usr/bin/wall; \
    chmod a-s usr/bin/gpasswd; \
    chmod u-s usr/bin/newgrp; \
    chmod g-s sbin/unix_chkpwd; \
    rm -rf /var/lib/apt/lists

WORKDIR /etc/nginx/

COPY nginx/nginx.conf .
COPY server/ ./server/

CMD cd server; bash run.sh

#USER student
